<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>OpenSense.Service</AssemblyName>
    <RootNamespace>OpenSense.Service</RootNamespace>
    <ApplicationIcon>..\OpenSense.App\Assets\OpenSense.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenSense.Core\OpenSense.Core.csproj" />
  </ItemGroup>

</Project>
